# <u> Copulax Examples </u>

## Correlation and Covariance Estimation

CopulAX provides a number of estimators for both the correlation and covariance matrices. These methods are conviently wrapped in the `corr` and `cov` functions.

### Estimating the Correlation Matrix

In [1]:
# generating a random sample
import numpy as np
dim = 3
sample = np.random.normal(loc=0, scale=1, size=(100, dim)) * np.random.standard_t(df=5, size=(100, dim))
sample[:, 1] = sample[:, 0] + sample[:, 1]
sample[:, 2] = abs(sample[:, 2])

# estimating the correlation matrix
from copulax.multivariate import corr
corr_matrix = corr(sample, method='spearman')
print("Estimated correlation matrix:")
print(corr_matrix)

Estimated correlation matrix:
[[ 1.          0.57287735  0.00838884]
 [ 0.57287735  1.         -0.03144315]
 [ 0.00838884 -0.03144315  1.        ]]


### Estimating the Covariance Matrix

In [2]:
# estimating the covariance matrix
from copulax.multivariate import cov
cov_matrix = cov(sample, method='spearman')
print("Estimated covariance matrix:")
print(cov_matrix)

Estimated covariance matrix:
[[ 0.79703313  0.73155475  0.00925294]
 [ 0.7315548   2.0459454  -0.05556648]
 [ 0.00925294 -0.05556648  1.5264401 ]]


## Correlation and Covariance Matrix Sampling

CopulAX provides random uniform samplers for both the correlation and covariance matrices.
As copulAX is JAX based, a key is required for random number generation. 
Random keys can be generated using copulAX's `get_random_key` function, as shown below.

### Sampling the Correlation Matrix

In [3]:
# generating a random key
from copulax import get_random_key
from jax.random import split
key = get_random_key()
correlation_key, covariance_key = split(key)

# generating a random correlation matrix
from copulax.multivariate import random_correlation
dim = 5
rand_corr = random_correlation(size=dim, key=correlation_key)
print("Random correlation matrix:")
print(rand_corr)

Random correlation matrix:
[[ 1.         -0.2863497   0.1539065  -0.8012594  -0.33014324]
 [-0.28634974  0.9999999  -0.2915295   0.21791357  0.2516172 ]
 [ 0.1539065  -0.2915295   0.99999994 -0.16484474  0.06449151]
 [-0.8012594   0.21791354 -0.16484474  0.9999999   0.4024159 ]
 [-0.33014324  0.2516172   0.06449151  0.4024159   1.        ]]


### Sampling the Correlation Matrix
Unlike when sampling the correlation matrix, when we sample the covariance matrix, we must specify the variance of each variable.

In [4]:
# generating a random covariance matrix
from copulax.multivariate import random_covariance
variances = np.random.uniform(low=0.1, high=2.0, size=dim)
rand_cov = random_covariance(vars=variances, key=covariance_key)
print("Random covariance matrix:")
print(rand_cov)

Random covariance matrix:
[[ 0.26876247 -0.39513734  0.15230891 -0.3426704  -0.14799194]
 [-0.39513737  1.849741   -0.11112267  1.0092597   0.06406494]
 [ 0.15230891 -0.11112267  1.1897591  -0.27854618  0.03428948]
 [-0.3426704   1.0092598  -0.27854618  1.9918437   0.09132448]
 [-0.14799194  0.06406493  0.03428948  0.09132448  1.4250162 ]]
