# <u> Copulax Examples </u>

## Correlation and Covariance Estimation

CopulAX provides a number of estimators for both the correlation and covariance matrices. These methods are conviently wrapped in the `corr` and `cov` functions.

### Estimating the Correlation Matrix

In [9]:
# generating a random sample
import numpy as np
dim = 3
sample = np.random.normal(loc=0, scale=1, size=(100, dim)) * np.random.standard_t(df=5, size=(100, dim))
sample[:, 1] = sample[:, 0] + sample[:, 1]
sample[:, 2] = abs(sample[:, 2])

# estimating the correlation matrix
from copulax.multivariate import corr
corr_matrix = corr(sample, method='spearman')
print("Estimated correlation matrix:")
print(corr_matrix)

Estimated correlation matrix:
[[ 1.          0.73582965 -0.04146415]
 [ 0.73582965  1.          0.07059106]
 [-0.04146415  0.07059106  1.        ]]


### Estimating the Covariance Matrix

In [10]:
# estimating the covariance matrix
from copulax.multivariate import cov
cov_matrix = cov(sample, method='spearman')
print("Estimated covariance matrix:")
print(cov_matrix)

Estimated covariance matrix:
[[ 1.1512595   1.657448   -0.05855984]
 [ 1.657448    4.407091    0.19505909]
 [-0.05855983  0.19505909  1.7325306 ]]


## Correlation and Covariance Matrix Sampling

CopulAX provides random uniform samplers for both the correlation and covariance matrices.
As copulAX is JAX based, a key is required for random number generation. 
Random keys can be generated using copulAX's `get_random_key` function, as shown below.

### Sampling the Correlation Matrix

In [11]:
# generating a random key
from copulax import get_random_key
from jax.random import split
key = get_random_key()
correlation_key, covariance_key = split(key)

# generating a random correlation matrix
from copulax.multivariate import random_correlation
dim = 5
rand_corr = random_correlation(size=dim, key=correlation_key)
print("Random correlation matrix:")
print(rand_corr)

Random correlation matrix:
[[ 0.99999994 -0.49502462  0.55662817 -0.22947739  0.2891577 ]
 [-0.49502462  1.         -0.1153269   0.4333606  -0.35509455]
 [ 0.55662817 -0.1153269   1.         -0.12824138  0.11855949]
 [-0.22947739  0.4333606  -0.12824138  1.         -0.17411357]
 [ 0.2891577  -0.35509455  0.11855949 -0.17411357  1.0000001 ]]


### Sampling the Correlation Matrix
Unlike when sampling the correlation matrix, when we sample the covariance matrix, we must specify the variance of each variable.

In [12]:
# generating a random covariance matrix
from copulax.multivariate import random_covariance
variances = np.random.uniform(low=0.1, high=2.0, size=dim)
rand_cov = random_covariance(vars=variances, key=covariance_key)
print("Random covariance matrix:")
print(rand_cov)

Random covariance matrix:
[[ 0.33045653 -0.13753434  0.21196383  0.06495499  0.1788552 ]
 [-0.13753434  0.16292171 -0.1444542   0.00866764 -0.28432825]
 [ 0.2119638  -0.1444542   1.9527243  -0.3477549   0.49384645]
 [ 0.06495499  0.00866764 -0.3477549   1.7587712  -0.40990657]
 [ 0.17885518 -0.28432828  0.49384645 -0.4099066   0.92818105]]
